Update invoke.yml

diff --git a/.github/workflows/invoke.yml b/.github/workflows/invoke.yml
--- a/.github/workflows/invoke.yml
+++ b/.github/workflows/invoke.yml
@@ -121,10 +121,10 @@ jobs:
   #       run: |
   #         echo "single_deploy.yml URL: ${{ steps.trigger-step.outputs.workflow-url }}"
 
-  #     - name: Check triggered workflow status
-  #       if: always()
-  #       run: |
-  #         if [ ${{ steps.trigger-step.outputs.workflow-conclusion }} != 'success' ] ; then
-  #           echo "Triggered workflow failed"
-  #           exit 1
-  #         fi  
+      - name: Check triggered workflow status
+        if: always()
+        run: |
+          if [ ${{ steps.trigger-step.outputs.workflow-conclusion }} != 'success' ] ; then
+            echo "Triggered workflow failed"
+            exit 1
+          fi  
